sudo: false
dist: trusty
language: rust
cache: cargo
rust: stable
addons:
  apt:
    packages:
      - aspell
      - aspell-en

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --debug --force mdbook)
  - (test -x $HOME/.cargo/bin/mdbook-linkcheck || cargo install --debug --force mdbook-linkcheck)
  - cargo install-update -a

script:
  - mdbook build

before_cache:
  - find ./target/debug -maxdepth 1 -type f -delete
  - rm -rf ./target/debug/incremental
  - rm -rf ./target/debug/{deps,.fingerprint}/[0-9][0-9]_[0-9][0-9]_*
  - rm -f ./target/.rustc_info.json

env:
  RUSTINFRA_DEPLOY_DIR: book
  GITHUB_DEPLOY_KEY: No
import:
  - rust-lang/simpleinfra:travis-configs/static-websites.yml
